

services:
  postgres:
    image: postgres:16-alpine
    container_name: securityrota-db
    environment:
      POSTGRES_USER: rota
      POSTGRES_PASSWORD: rotapass
      POSTGRES_DB: securityrota
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

